### PR TITLE
project 1

### PR DESCRIPTION
**Pull request by yadavsairaj**
adding codeowners file

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by ghost** [comment]
Reviewing this right now, let's see...

**Review by ghost — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Comment by yadavsairaj** [comment]
[CODEOWNERS.docx](https://github.com/ObelusFamily/Anythink-Market-kmz7z/files/9235886/CODEOWNERS.docx)

**Review by yadavsairaj — COMMENTED** [review]
[CODEOWNERS.docx](https://github.com/ObelusFamily/Anythink-Market-kmz7z/files/9235907/CODEOWNERS.docx)

**Comment by yadavsairaj** [comment]
done please check

**Comment by yadavsairaj** [comment]
done

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Hmm, looks like **there is no `CODEOWNERS` file** in the PR you've opened. We need it.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Review by yadavsairaj — COMMENTED** [review]
done

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Review by yadavsairaj — COMMENTED** [review]
check

**Comment by yadavsairaj** [comment]
start_quest.sh

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Hmm, looks like **there is no `CODEOWNERS` file** in the PR you've opened. We need it.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Hmm, looks like **there is no `CODEOWNERS` file** in the PR you've opened. We need it.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Review by yadavsairaj — COMMENTED** [review]
Please review

**Pull request closed without merging**
